url: ""

# Google tracking id
google-tracking-id: "UA-111273208-1"

#############
# HTML Head #
#############

lang: "en"
author: "Anas Aboureada"
title: "{ Anas Aboureada }"
description: "Blog and website of Anas Aboureada, blogging mainly about cyber security. Opinions expressed are mine."
keywords: "aboureada, anas, blog, anasfullstack, full-stack web developer, penetration testing, reverse engineering"
favicon: "/assets/img/icon.png"

################
# Header layout #
################

black-favicon: "/assets/img/icon.png"

background-img: "/assets/img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: false # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2000
lines:
  - text: "Full Stack Web Developer Engineer."
  - text: "Software Engineer"

me-img: "assets/img/me-intro.jpg"
author-img: "author.jpg"
# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"
# me-img: "https://github.com/user_name.png?size=500"
# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

############
# Timeline #
############

events:
  - image: "/assets/img/timeline/zoover.png"
    date: " 2018 - Now"
    location: "Amsterdam, The Netherlands"
    description: "Full-Stack Web Developer"
  - image: "/assets/img/timeline/doremir.png"
    date: " 2015 - 2018"
    location: "Stockholm, Sweden"
    description: "Full-Stack Web Developer"
  - image: "/assets/img/timeline/globalmouth.png"
    date: "2015"
    location: "Stockholm, Sweden"
    description: "Front-End Web Developer"
  - image: "/assets/img/timeline/madar.png"
    date: "2014 - 2015"
    location: "Alexandria, Egypt"
    description: "Web / Hybrid Application Developer"
  - image: "/assets/img/timeline/messile.jpg"
    date: "2011 - 2014"
    location: "Egyptian Armed Forces"
    description: "Missile Engineer"
  - image: "/assets/img/timeline/college.jpg"
    date: "2011"
    location: "Faculty of Engineering, Alexandria University, Egypt"
    description: "Graduted with BSE degree"
  - image: "/assets/img/timeline/student.png"
    date: "2003 - now"
    location: "Alexandria, Egypt"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/assets/img/timeline/baby.png"

###########
# Contact #
###########

email: "anas@aboureada.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Full-Stack Web Developer Engineer, Studying for OSCP"
author_blurb_image: "/assets/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/anasfullstack"
  - title: "twitter"
    url: "https://twitter.com/anasfullstack"
  - title: "github"
    url: "https://github.com/anasfullstack"

############
# 404 page #
############

err-404-img: "/assets/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: anasfullstack
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE",
"README.md",
"Gemfile",
"Gemfile.lock",
"vendor"
]

# Pagination path

paginate_path: "/blog/page/:num/"

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-archives
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - liquid_pluralize
  - jekyll-twitter-plugin

########
# Blog #
########

enable-gesture-navigation: True
post-preview-words: 96
paginate: 20
disqus-shortname: "aboureada-com"
syntax-highlight: True

about-author: Web Developer Engineer & Penetration Tester.
twitter: anasfullstack
facebook: anasfullstack
github: anasfullstack
linkedin: anasfullstack
email: anas@aboureada.com

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'


######################
#    SEO             #
######################

logo: "/assets/img/icon.png"

sass:
  sass_dir: _sass
  style: compressed
